### ISSUE TITLE
Reorganize this repository

### ISSUE THREAD

**Issue by mcastel** [gclusters/gclusters#6]
This repository needs some reorganizing of files and directories, in order to make the project more understandable and more friendly to use...

**Comment by lbmm** [comment]
questions: 
1- temp.txt can this be removed ? 
2- SQL structure: do we have an installation script in place ?and if yes where the directory need to sit ?
3- mystyles.css :  i did search and there is no reference to the file. How styles are used ?

thanks

**Comment by lbmm** [comment]
i created a new branch with a tentative repo reorganizzation. 
the commit messages are wrong, my bad! 

Please have a look to the branch and raise all questions that you could have. 

when i have 10 min I will send you an email with some informations and share my thoughts about decision that I have made. But first of all this is the very first reorganization. More will come :-)

**Comment by lbmm** [comment]
details of the commits: 

https://github.com/gclusters/gclusters/commit/53eadb33852db4019d5c912fc733e74f023b68d1

**Comment by mcastel** [comment]
Hello! just some quick replies to your well posed questions...
1. Yes, temp.txt is not useful. I removed it from repository (at least, I hope to have removed it!)
2. Concerning SQL, I put the SLQ script in the folder SQL/. This script should recreate the needed tables for the project, and should consistently populate them with a minimal set of data (four clusters, with related parameters, images, links and bibliographics items). Anyway it has not properly tested yet.
3. the residual CSS "mystyles.css" file is just a sign of an attempt to adopt CSS that actually went not too far... as a consequence, I do believe the file is not used by any page and it should be safely to remove.

Browsing the details of your commit, @lbmm, I have discovered that source files are changed consistently with new absolute URL address ... I wonder how you obtained it!

**Comment by lbmm** [comment]
done ! after many months :( 

1- moved ima and graph into static folder
2- renamed the path into the php scripts
3- fixed typos of the images

**Comment by lbmm** [comment]
if there are not other comment I would close the issue

**Comment by mcastel** [comment]
Thanks @lbmm, it's ok for me to close this issue.

**Comment by lbmm** [comment]
ok. closing this issue
